<script setup>
import { ref,computed,watch,onMounted } from 'vue'
import DataTable from './DataTable.vue'
const report=ref(null),error=ref(''),busy=ref(false),category=ref(''),risk=ref(''),query=ref(''),page=ref(1),selected=ref(null)
const money=v=>v==null?'—':'¥'+Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
const num=v=>v==null?'不可计算':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:1})
const pct=v=>v==null?'不可计算':(v*100).toFixed(1)+'%'
const filtered=computed(()=>(report.value?.inventory||[]).filter(r=>(!category.value||r.category===category.value)&&(!risk.value||r.flags.includes(risk.value))&&(!query.value||(r.sku_id).toLowerCase().includes(query.value.toLowerCase()))).sort((a,b)=>b.ending_inventory_cost-a.ending_inventory_cost))
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/12)))
const flags=['覆盖不足','供给受限','去化缓慢','近期无出库','常规观察']
watch([category,risk,query],()=>{page.value=1;selected.value=null})
async function reload(){busy.value=true;error.value='';try{const response=await fetch('/api/business-decisions');const data=await response.json();if(!response.ok)throw new Error(data.detail||'加载失败');report.value=data;selected.value=null;page.value=1}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(reload);defineExpose({reload})
</script>
<template>
<section class="business">
 <article class="panel"><div class="panel-heading"><h3>商业数据决策 · 经营信号如何反馈选品</h3><span class="badge amber">模拟数据 / 建议待验证</span></div><p>核对订单与库存 → 区分售出、周转和可售天数 → 识别供给与去化风险 → 提出下一轮商品假设 → 小批量验证。</p><div class="controls"><a class="button white" href="/api/business-decisions?download=markdown">导出分析报告</a><a class="button white" href="/api/business-decisions?download=json">导出指标与决策依据</a></div></article>
 <p v-if="busy">正在核对日库存流量、订单请求与采购入库…</p><p v-if="error" class="error">{{error}}</p>
 <template v-if="report">
  <div class="stats">
   <article class="panel"><span>窗口售出占比</span><strong>{{pct(report.summary.period_sell_through)}}</strong><small>出库 /（出库 + 期末库存）</small></article>
   <article class="panel"><span>库存周转天数</span><strong>{{num(report.summary.inventory_turnover_days)}} 天</strong><small>平均库存成本 / 窗口出库成本 × 天数</small></article>
   <article class="panel"><span>期末库存成本</span><strong>{{money(report.summary.ending_inventory_cost)}}</strong><small>成本占用，不是零售货值</small></article>
   <article class="panel"><span>去化风险SKU</span><strong>{{report.summary.slow_skus}}</strong><small>相关库存成本 {{money(report.summary.slow_stock_cost)}} · 非节省金额</small></article>
  </div>
  <article class="panel"><h3>先确认指标口径</h3><p>{{report.period_start}}—{{report.period_end}}，{{report.summary.skus}}个SKU、{{report.summary.inventory_snapshots.toLocaleString()}}条库存快照。已核对日库存流量、跨日期初期末衔接、采购入库及订单请求。</p><p>支付订单商品 {{report.quality.paid_order_units.toLocaleString()}}件；库存实际出库 {{report.summary.outbound_units.toLocaleString()}}件；未满足出库请求 {{report.summary.unmet_units}}件。{{report.quality.note}}</p><div class="definitions"><div><h4>售出占比 ≠ 单批次售罄率</h4><p>连续补货下采用窗口出库 /（窗口出库 + 期末库存）。缺少批次追踪，不能称为某一生产批次售罄率。</p></div><div><h4>周转天数 ≠ 剩余可售天数</h4><p>周转描述过去的库存占用；可售天数用期末可用库存 / 近{{report.summary.recent_days}}天日均出库，评估后续覆盖。无出库时不显示0天。</p></div><div><h4>风险标签 ≠ 已确认积压</h4><p>近期无出库，或可售天数超过{{report.policy.slow_cover_days}}天且售出占比低于{{pct(report.policy.low_sell_through)}}时提示去化风险。没有批次库龄，无法确认实际积压时长。</p></div></div><p class="notice">{{report.policy.assumption_notice}}</p></article>
  <article class="panel table-panel"><div class="panel-heading"><h3>品类经营比较</h3><span class="badge gray">金额加总后计算，不平均各SKU比率</span></div><DataTable :rows="report.categories" :columns="[{key:'category',label:'品类'},{key:'outbound_units',label:'出库件数',type:'number'},{key:'ending_units',label:'期末库存',type:'number'},{key:'sell_through',label:'售出占比',type:'percent'},{key:'turnover_days',label:'周转天数',type:'number'},{key:'ending_cost',label:'期末库存成本',type:'money'}]"/></article>
  <article class="panel"><h3>从库存信号到运营动作</h3><div class="counts"><span v-for="f in flags" :key="f">{{f}}：{{report.summary.flag_counts[f]||0}}个</span></div><p class="muted">标签可重叠。覆盖不足指可售天数短于补货周期加{{report.policy.service_buffer_days}}天缓冲；供给受限指存在未满足请求且占比达到{{pct(report.policy.shortage_rate)}}。均需核对在途采购后执行。</p><div class="filters"><label>品类<select v-model="category" aria-label="决策品类"><option value="">全部品类</option><option v-for="r in report.categories" :key="r.category">{{r.category}}</option></select></label><label>风险信号<select v-model="risk" aria-label="风险信号"><option value="">全部信号</option><option v-for="f in flags" :key="f">{{f}}</option></select></label><label>角色 / 商品<input v-model="query" aria-label="搜索决策商品" placeholder="输入角色或品类"/></label></div></article>
  <article class="panel table-panel"><div class="panel-heading"><h3>SKU诊断 · {{filtered.length}}个</h3><span class="muted">按库存成本排序 · 点击查看改进假设</span></div><DataTable :rows="filtered.slice((page-1)*12,page*12)" action="查看决策依据" @select="selected=$event" :columns="[{key:'operator',label:'角色'},{key:'category',label:'品类'},{key:'risk',label:'风险信号'},{key:'period_sell_through',label:'售出占比',type:'percent'},{key:'inventory_turnover_days',label:'周转天数',type:'number'},{key:'available_cover_days',label:'可售天数',type:'number'},{key:'ending_inventory_cost',label:'库存成本',type:'money'}]"/><div class="pager"><button class="button white" :disabled="page<=1" @click="page--">上一页</button><span>{{page}} / {{pages}}</span><button class="button white" :disabled="page>=pages" @click="page++">下一页</button></div></article>
  <article v-if="selected" class="panel detail"><div class="panel-heading"><h3>{{selected.sku_id}} · 决策依据</h3><button class="button white" @click="selected=null">收起依据</button></div><p><b>现象：</b>{{selected.risk}}。售出占比{{pct(selected.period_sell_through)}}，周转{{num(selected.inventory_turnover_days)}}天，可售{{num(selected.available_cover_days)}}天；补货周期{{selected.lead_days}}天。</p><p><b>核对依据：</b>期初{{selected.opening_units}} + 采购入库{{selected.inbound_units}} + 可再售退回{{selected.restockable_return_units}} − 出库{{selected.outbound_units}} = 期末{{selected.ending_units}}件；近{{report.summary.recent_days}}天出库{{selected.recent_outbound_units}}件。</p><p><b>运营动作：</b>{{selected.suggested_action}}</p><p><b>下一轮产品定义假设：</b>{{selected.next_product_hypothesis}}</p><p><b>验证路径：</b>{{selected.verification}}</p><p class="notice">{{selected.evidence_scope}}</p></article>
  <article class="panel table-panel"><div class="panel-heading"><h3>ROI与盈亏平衡 · 延用GMV营销假设</h3><a class="button white" href="#gmv">进入营销测算</a></div><p class="inset muted">下表是基准与4类营销方案的独立情景测算。ROI =（扣退款收入 − 所列成本）/ 所列成本；成本含商品、履约、赠品、平台及推广，不含固定成本和税费。销售额/推广费假设全部销售归因于推广，不代表实际ROAS。</p><DataTable :rows="report.scenarios" :columns="[{key:'name',label:'情景'},{key:'paid_merchandise_gmv',label:'假设GMV',type:'money'},{key:'modeled_total_cost',label:'口径内总成本',type:'money'},{key:'contribution_profit',label:'假设贡献利润',type:'money'},{key:'modeled_roi',label:'假设ROI',type:'percent'},{key:'scenario_revenue_to_ad_spend',label:'销售额/推广费',type:'number'},{key:'breakeven_orders',label:'推广盈亏平衡订单',type:'number'}]"/></article>
  <article class="panel"><div class="panel-heading"><h3>用户LTV · {{report.ltv.status}}</h3><span class="badge gray">缺少用户级购买历史</span></div><p>{{report.ltv.reason}}</p><p>{{report.ltv.next_step}}</p><details><summary>需要补充的数据</summary><ul><li v-for="text in report.ltv.required" :key="text">{{text}}</li></ul></details></article>
  <article class="panel"><h3>分析边界与参考口径</h3><ul><li v-for="text in report.limitations" :key="text">{{text}}</li></ul><div class="controls"><a v-for="s in report.sources" :key="s.url" :href="s.url" target="_blank" rel="noreferrer">{{s.title}}</a></div></article>
 </template>
</section>
</template>
<style scoped>
.business{display:grid;gap:22px}.business p,.business li{font-size:13px;line-height:1.85}.business ul{padding-left:22px}.business .panel-heading{flex-wrap:wrap;gap:12px}.controls,.counts,.pager{display:flex;flex-wrap:wrap;gap:14px;align-items:center}.controls a{font-size:12px}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.stats article{display:grid;gap:12px}.stats strong{font-size:23px;color:#36543a;overflow-wrap:anywhere}.stats small,.stats span{font-size:12px;color:#637168}.definitions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.definitions h4{font-size:14px}.notice{padding:12px 16px;background:#fff6e6;border-left:3px solid #be903c;color:#725621}.inset{padding:0 24px}.filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.filters label{display:grid;gap:8px;font-size:12px}.filters select,.filters input{padding:10px;max-width:100%;box-sizing:border-box;border:1px solid #dfe7df;background:white;border-radius:6px}.counts span{padding:8px 12px;background:#eef4eb;border-radius:6px;font-size:12px}.pager{padding:20px 24px;justify-content:flex-end;font-size:12px}.detail{border-top:3px solid #799678}.error{color:#a23932}.business summary{font-size:13px;cursor:pointer}@media(max-width:1100px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.filters,.definitions{grid-template-columns:1fr}}
</style>
