<script setup>
import { ref, onMounted } from 'vue'
import { Download, RefreshCw } from 'lucide-vue-next'
import DataTable from './DataTable.vue'

const report=ref(null), error=ref(''), busy=ref(false), search=ref('')
async function load(){busy.value=true;error.value='';try{const response=await fetch('/api/decision-evidence');const body=await response.json();if(!response.ok)throw Error(body.detail||'加载失败');report.value=body}catch(caught){error.value=caught.message}finally{busy.value=false}}
const money=value=>Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
onMounted(load)
</script>

<template>
  <section class="decision-evidence">
    <div class="toolbar"><span class="muted">九个追问 · 业务问题 → 数据证据 → 方法验证 → 执行边界</span><div class="toolbar-actions"><button class="button white" @click="load" :disabled="busy"><RefreshCw :size="14"/>重新计算</button><a class="button primary" href="/api/decision-evidence?download=true"><Download :size="14"/>导出证据报告</a></div></div>
    <p v-if="busy" role="status" class="section-notice">正在用固定随机种子重算敏感性，并执行SQL对账…</p>
    <p v-if="error" role="alert" class="error-banner">{{ error }}</p>
    <template v-if="report">
      <div class="section-notice">{{ report.claim_boundary }}</div>
      <div class="brief-grid"><article v-for="question in report.business_questions" :key="question.decision" class="brief-card"><span class="badge gray">01 / 决策目标</span><h3>{{ question.decision }}</h3><p><b>依据</b>{{ question.basis }}</p><p><b>下一步</b>{{ question.next }}</p><p><b>尚未证明</b>{{ question.not_proven }}</p></article></div>
      <article class="panel table-panel"><div class="panel-heading"><div><h3>02 / 数据来源与证据性质</h3><p>同一受访者的排序与价格回答，不重复计作独立用户</p></div></div><DataTable :rows="report.sources" :columns="[{key:'source',label:'来源'},{key:'scope',label:'粒度',class:'wide-cell'},{key:'record_count',label:'记录',type:'number'},{key:'data_nature',label:'性质'},{key:'decision_use',label:'用途'}]"/></article>
      <article class="panel"><h3>03 / 跨平台可比性审计</h3><p class="muted spaced">{{ report.content.method }}</p><p class="muted spaced">{{ report.content.scoring_scope }}</p><p class="section-notice">{{ report.content.association_rows }} 条角色关联 → {{ report.content.unique_content }} 条独立内容；重复关联 {{ report.content.duplicate_role_links }} 条。分摊后的内容当量 {{ report.content.fractional_content_total.toFixed(2) }}，不冒充去重人数。</p><DataTable :rows="report.content.cohorts" :columns="[{key:'platform',label:'平台'},{key:'age_band',label:'发布年龄'},{key:'unique_content',label:'独立内容',type:'number'},{key:'role_links',label:'角色关联',type:'number'},{key:'fractional_content',label:'分摊内容当量',type:'number'}]"/><details open><summary>必须带着这些限制理解排行榜</summary><ul class="evidence-notes"><li v-for="note in report.content.limitations" :key="note">{{ note }}</li></ul></details></article>
      <article class="panel table-panel"><div class="panel-heading"><div><h3>04 / 权重与排名稳定性</h3><p>{{ report.robustness.operator_count }}名角色 · {{ report.robustness.scenario_count }}组情景 · 随机种子{{ report.robustness.seed }}</p></div><input v-model="search" placeholder="搜索角色稳定性" aria-label="搜索角色稳定性"/></div><div class="metric-definition">{{ report.robustness.weight_basis }}<br/>{{ report.robustness.method }}<br/>{{ report.robustness.boundary }}</div><DataTable :rows="report.robustness.operators.filter(row=>row.operator.includes(search))" :columns="[{key:'operator',label:'角色',class:'primary-cell'},{key:'baseline_rank',label:'均衡排名',type:'number'},{key:'best_rank',label:'最好',type:'number'},{key:'worst_rank',label:'最差',type:'number'},{key:'perturb_top_k_share',label:'扰动Top-'+report.robustness.top_k+'占比',type:'percent'},{key:'evidence_sources',label:'来源数',type:'number'},{key:'next_action',label:'如何使用',class:'wide-cell'}]"/><details class="metric-definition"><summary>查看五种权重与四种去源实验</summary><DataTable :rows="report.robustness.scenarios.filter(row=>!row.scenario.startsWith('perturb_')).map(row=>({...row,weights:JSON.stringify(row.weights)}))" :columns="[{key:'scenario',label:'情景'},{key:'weights',label:'content / survey / skland / commerce',class:'wide-cell'},{key:'top_k_jaccard',label:'Top集合交并比',type:'percent'},{key:'rank_correlation',label:'名次相关',type:'number'},{key:'ranked_count',label:'有效角色',type:'number'}]"/></details></article>
      <article class="panel table-panel"><div class="panel-heading"><div><h3>05 / 问卷发现如何转为行动</h3><p>{{ report.survey.response_count }}份回收 · {{ report.survey.high_intent_count }}人高意愿，不是已支付买家</p></div></div><div class="metric-definition">{{ report.survey.boundary }}</div><DataTable :rows="report.survey.categories" :columns="[{key:'category',label:'品类'},{key:'respondent_count',label:'组内样本',type:'number'},{key:'high_intent_share',label:'高意愿',type:'percent'},{key:'next_action',label:'动作',class:'wide-cell'}]"/></article>
      <article class="panel"><h3>06 / 商品身份与人工复核</h3><p class="muted spaced">{{ report.catalog.grain }}</p><p class="section-notice">{{ report.catalog.snapshot_rows }}条快照 / {{ report.catalog.unique_item_links }}个商品链接 / {{ report.catalog.review_count }}个身份歧义待复核；缺少ID {{ report.catalog.missing_id_rows }}条。</p><p class="muted spaced">{{ report.catalog.policy }}</p><DataTable :rows="report.catalog.conflicts" :columns="[{key:'item_id',label:'商品链接ID',class:'mono'},{key:'snapshot_count',label:'观测数',type:'number'},{key:'reason',label:'为什么不能自动归并/归因',class:'wide-cell'}]"/></article>
      <article class="panel"><h3>07—08 / SQL与模拟ERP：一次可复核的金额防重复案例</h3><p class="muted spaced">{{ report.sql_case.method }}</p><div class="brief-grid"><div class="brief-card"><b>直接连接明细后相加（错误示范）</b><strong>¥{{ money(report.sql_case.naive_join_paid_amount_incorrect) }}</strong><small>重复放大 ¥{{ money(report.sql_case.duplicate_amplification) }}</small></div><div class="brief-card"><b>按订单粒度汇总后（正确）</b><strong>¥{{ money(report.sql_case.sql_paid_amount) }}</strong><small>{{ report.sql_case.paid_order_count }}张支付订单</small></div><div class="brief-card"><b>与原始订单头独立对账</b><strong>{{ report.sql_case.reconciliation_passed?'通过':'不通过' }}</strong><small>订单头金额 ¥{{ money(report.sql_case.expected_paid_amount) }}</small></div></div><p class="muted spaced">{{ report.sql_case.boundary }}</p><DataTable :rows="report.sql_case.channels" :columns="[{key:'channel',label:'渠道'},{key:'paid_orders',label:'支付订单',type:'number'},{key:'paid_amount',label:'支付含运费',type:'money'},{key:'closed_refund_amount',label:'已关闭退款',type:'money'},{key:'line_mismatch_orders',label:'头明细金额异常',type:'number'}]"/><details><summary>查看真实执行的SQL</summary><pre class="evidence-code">{{ report.sql_case.query }}</pre></details></article>
      <article class="panel table-panel"><div class="panel-heading"><div><h3>09 / 建议、批准和真实执行分开记录</h3><p>{{ report.execution.boundary }}</p></div></div><DataTable :rows="report.execution.approvals" :columns="[{key:'candidate_id',label:'候选'},{key:'decision',label:'审批'},{key:'decided_at',label:'日期'},{key:'rationale',label:'批准范围',class:'wide-cell'},{key:'evidence_ref',label:'依据',class:'wide-cell'}]"/><DataTable :rows="report.execution.stages" :columns="[{key:'stage',label:'阶段'},{key:'current_value',label:'记录数值',type:'number'},{key:'status',label:'状态',type:'badge'},{key:'gate',label:'门槛',class:'wide-cell'},{key:'next_action',label:'还缺什么',class:'wide-cell'}]"/></article>
      <article class="panel"><details><summary>复现清单 · {{ report.manifest.length }}份输入与SQL指纹</summary><p class="muted spaced">SHA-256用于定位输入版本，不证明数据真实性或结论有效性。旧静态报告需重新生成才能反映后续输入变化。</p><DataTable :rows="report.manifest" :columns="[{key:'file',label:'输入文件',class:'wide-cell'},{key:'rows',label:'行数',type:'number'},{key:'sha256',label:'SHA-256',class:'wide-cell'}]"/></details></article>
    </template>
  </section>
</template>

<style scoped>
.decision-evidence{display:grid;gap:22px}.decision-evidence .toolbar{flex-wrap:wrap}.decision-evidence h3{line-height:1.6}.decision-evidence summary{cursor:pointer;font-size:13px;color:#41684c;padding:12px 0}.evidence-notes{padding-left:22px;font-size:12px;line-height:1.9;color:#637168}.evidence-code{white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f6ef;padding:18px;border-radius:8px;font-size:12px;line-height:1.7}.decision-evidence input{border:1px solid #dfe7df;padding:9px;border-radius:7px;max-width:180px}.decision-evidence .brief-card strong{font-size:22px;color:#36543a}.decision-evidence .panel-heading{flex-wrap:wrap;gap:12px}
</style>
