<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { LayoutDashboard, Package, Database, Users, ChartNoAxesCombined, Settings2, ArrowUpRight, ArrowRight, Search, Download, RefreshCw, ChevronRight, X, ShieldCheck, CheckCircle2, Clock3, Upload, CircleHelp, Layers3, PanelLeftClose, ExternalLink, Activity } from 'lucide-vue-next'
import TrendChart from './components/TrendChart.vue'
import Bars from './components/Bars.vue'
import DataTable from './components/DataTable.vue'
import OperationsBrief from './components/OperationsBrief.vue'
import DecisionEvidence from './components/DecisionEvidence.vue'
import OperationsTasks from './components/OperationsTasks.vue'
import ErpChecks from './components/ErpChecks.vue'
import LifecycleAnalysis from './components/LifecycleAnalysis.vue'
import GmvDrivers from './components/GmvDrivers.vue'
import ChannelStrategy from './components/ChannelStrategy.vue'
import BusinessDecisions from './components/BusinessDecisions.vue'
import profileAvatar from './assets/profile-avatar.jpg'
import brandAmiya from './assets/brand-amiya.png'

const tabs=[{id:'overview',name:'运营总览',en:'OPERATIONS OVERVIEW',icon:LayoutDashboard},{id:'products',name:'商品信息维护',en:'PRODUCT CATALOG',icon:Package},{id:'erp',name:'ERP 数据处理',en:'ERP OPERATIONS',icon:Database},{id:'research',name:'周边用户调研',en:'USER RESEARCH',icon:Users},{id:'selection',name:'角色与选品',en:'MERCHANDISE PLANNING',icon:ChartNoAxesCombined},{id:'settings',name:'数据与服务',en:'DATA & SERVICES',icon:Settings2}]
tabs.splice(5,0,{id:'decisions',name:'决策证据',en:'DECISION EVIDENCE',icon:ShieldCheck})
tabs.splice(5,0,{id:'lifecycle',name:'角色生命周期',en:'CHARACTER LIFECYCLE',icon:Activity})
tabs.splice(6,0,{id:'gmv',name:'GMV 驱动分析',en:'GMV DRIVERS',icon:ChartNoAxesCombined})
tabs.splice(7,0,{id:'channels',name:'渠道与 SKU 配置',en:'CHANNEL STRATEGY',icon:Layers3})
tabs.splice(8,0,{id:'business',name:'商业数据决策',en:'COMMERCIAL DECISIONS',icon:Database})
tabs.splice(1,0,{id:'tasks',name:'日常运营待办',en:'DAILY OPERATIONS',icon:CheckCircle2})
const initial=location.hash.slice(1)
const active=ref(tabs.some(tab=>tab.id===initial)?initial:'overview'), overview=ref(null), health=ref(null), datasets=ref({}), busy=ref(false), error=ref(''), toast=ref(''), sidebar=ref(false)
const domain=ref('internal'), query=ref(''), category=ref(''), pending=ref(false), page=ref(1), productRows=ref([]), erpTab=ref('orders'), orderQuery=ref(''), ordersPage=ref(1), orderTotal=ref(0), orderRows=ref([])
const orderChannel=ref(''), orderStart=ref(''), orderEnd=ref(''), reconciliation=ref(null), appliedOrderFilters=ref({}), detailLoading=ref(false)
const brief=ref(null)
const lifecycleView=ref(null)
const gmvView=ref(null)
const channelView=ref(null)
const businessView=ref(null)
const editing=ref(null), editForm=ref({}), reason=ref(''), saving=ref(false), modalError=ref(''), auditRows=ref([]), showAudit=ref(false), importRows=ref(null), importing=ref(false), showImport=ref(false), detail=ref(null), detailRows=ref([]), showHelp=ref(false)
const metadata=computed(()=>tabs.find(tab=>tab.id===active.value))
const money=value=>'¥'+Number(value||0).toLocaleString('zh-CN',{maximumFractionDigits:0})
const exactMoney=value=>'¥'+Number(value||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
const number=value=>Number(value||0).toLocaleString('zh-CN',{maximumFractionDigits:0})
const percent=value=>(Number(value||0)*100).toFixed(1)+'%'
const rows=name=>datasets.value[name]||[]
let noticeTimer, navigationToken=0
function notify(message) {toast.value=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>toast.value='',5000)}
async function api(path,options={}) {const response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});if(!response.ok){let body;try{body=await response.json()}catch{body={detail:'请求失败 '+response.status}};throw Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail))}return response.json()}
async function loadData(names) {const responses=await Promise.all(names.map(name=>api('/data/'+name+'?limit=1000')));names.forEach((name,index)=>datasets.value[name]=responses[index].items)}
async function loadProducts(){const requestedDomain=domain.value;const result=await api('/catalog/'+requestedDomain+'?limit=500');if(domain.value===requestedDomain)productRows.value=result.items}
function parameters(values){return new URLSearchParams(Object.fromEntries(Object.entries(values).filter(([,value])=>value!==''&&value!==false))).toString()}
let orderRequest=0
async function loadOrders(){const token=++orderRequest;const filters={...appliedOrderFilters.value};const [result,check]=await Promise.all([api('/data/orders?'+parameters({...filters,page:ordersPage.value,limit:20})),api('/erp/reconciliation?'+parameters(filters))]);if(token!==orderRequest)return;orderRows.value=result.items;orderTotal.value=result.total;reconciliation.value=check}
async function refresh(){const token=++navigationToken;busy.value=true;error.value='';try{
 if(!overview.value||active.value==='overview'){overview.value=await api('/overview');brief.value=await api('/operations/brief');await loadData(['demand','survey_barriers'])}
 if(!health.value) health.value=await api('/health')
 if(active.value==='products'){await loadProducts();auditRows.value=(await api('/audit')).items;await loadData(['dictionary'])}
 if(active.value==='erp'){await Promise.all([loadData(['inventory','replenishment','reasons','channels','erp_categories','aftersales']),loadOrders()]);brief.value=await api('/operations/brief')}
 if(active.value==='research') await loadData(['survey_categories','survey_operators','survey_prices','survey_barriers','survey_ages','survey_channels'])
 if(active.value==='selection') await loadData(['demand','portfolio'])
 if(active.value==='lifecycle') await lifecycleView.value?.reload()
 if(active.value==='gmv') await gmvView.value?.reload()
 if(active.value==='channels') await channelView.value?.reload()
 if(active.value==='business') await businessView.value?.reload()
 if(active.value==='settings'){health.value=await api('/health');await loadData(['evidence','dictionary'])}
 }catch(caught){error.value=caught.message}finally{if(token===navigationToken)busy.value=false}}
function navigate(id){active.value=id;sidebar.value=false;location.hash=id}
function openBriefTask(id){if(id==='products')domain.value='public';if(id==='erp')erpTab.value='replenishment';navigate(id)}
watch(active,()=>{query.value='';category.value='';page.value=1;refresh()})
watch(domain,async()=>{page.value=1;query.value='';category.value='';try{await loadProducts()}catch(caught){error.value=caught.message}})
watch([query,category,pending],()=>page.value=1)
const matchesQuery=row=>!query.value||Object.values(row).some(value=>String(value??'').toLowerCase().includes(query.value.toLowerCase()))
const filteredProducts=computed(()=>productRows.value.filter(row=>(!category.value||row.category===category.value)&&(!pending.value||(domain.value==='public'?row.verification_status==='pending':row.rule_issue_count>0))&&matchesQuery(row)))
const productPage=computed(()=>filteredProducts.value.slice((page.value-1)*12,page.value*12))
const productColumns=computed(()=>domain.value==='internal'?[{key:'sku_code',label:'SKU 编码',class:'mono'},{key:'product_name',label:'商品名称',class:'primary-cell'},{key:'category',label:'品类'},{key:'price',label:'售价',type:'money'},{key:'unit_cost',label:'成本',type:'money'},{key:'gross_margin_rate',label:'规划毛利率',type:'percent'},{key:'sku_status',label:'生命周期',type:'badge'}]:[{key:'operator',label:'角色',class:'primary-cell'},{key:'category',label:'品类'},{key:'list_price',label:'展示价格',type:'money'},{key:'rights_type',label:'页面授权标注',type:'badge'},{key:'fulfillment_type',label:'履约类型'},{key:'verification_status',label:'人工核验',type:'badge'},{key:'data_quality_score',label:'质量分',type:'number'}])
const orderColumns=[{key:'order_id',label:'订单编号',class:'mono'},{key:'order_date',label:'下单日期'},{key:'channel',label:'销售渠道'},{key:'order_amount',label:'商品金额',type:'money'},{key:'discount_amount',label:'优惠',type:'money'},{key:'paid_amount',label:'实付',type:'money'},{key:'payment_status',label:'支付状态',type:'badge'},{key:'fulfillment_status',label:'履约状态',type:'badge'}]
const inventoryColumns=[{key:'operator',label:'角色',class:'primary-cell'},{key:'category',label:'品类'},{key:'ending_inventory',label:'期末库存',type:'number'},{key:'days_of_inventory',label:'可售天数',type:'number'},{key:'abc_xyz_class',label:'ABC–XYZ',type:'badge'},{key:'net_sales_after_refund',label:'退款后净销售',type:'money'},{key:'operating_action',label:'运营建议',class:'wide-cell'}]
const replenishmentColumns=[{key:'operator',label:'角色',class:'primary-cell'},{key:'category',label:'品类'},{key:'available_stock',label:'可售',type:'number'},{key:'open_po_units',label:'在途',type:'number'},{key:'suggested_po_quantity',label:'建议采购',type:'number'},{key:'suggested_purchase_amount',label:'采购预算',type:'money'},{key:'replenishment_priority',label:'优先级',type:'badge'}]
const demandColumns=[{key:'demand_rank',label:'排名',type:'number'},{key:'operator',label:'角色',class:'primary-cell'},{key:'content_signal',label:'内容信号',type:'number'},{key:'survey_signal',label:'问卷信号',type:'number'},{key:'skland_signal',label:'森空岛信号',type:'number'},{key:'commerce_signal',label:'商业信号',type:'number'},{key:'demand_score',label:'综合需求分',type:'number'},{key:'evidence_source_count',label:'证据来源',type:'number'},{key:'decision_note',label:'选品建议',class:'wide-cell'}]
const selectedErp=computed(()=>rows(erpTab.value).filter(row=>(!category.value||row.category===category.value)&&matchesQuery(row)))
const visibleDemand=computed(()=>rows('demand').filter(matchesQuery))
function exportData(name){let filters={};if(name==='orders')filters=appliedOrderFilters.value;else if(['internal','public'].includes(name))filters={q:query.value,category:category.value,pending:pending.value};else if(['inventory','replenishment'].includes(name))filters={q:query.value,category:category.value};else if(name==='demand')filters={q:query.value};window.location.assign('/api/export/'+name+'?'+parameters(filters))}
async function openEditor(row){editing.value=row;reason.value='';modalError.value='';editForm.value=domain.value==='internal'?{product_name:row.product_name,supplier_id:row.supplier_id,price:row.price,unit_cost:row.unit_cost,safety_stock:row.safety_stock,reorder_point:row.reorder_point,purchase_lead_time_days:row.purchase_lead_time_days,sku_status:row.sku_status}:{product_title:row.product_title,operator:row.operator,category:row.category,list_price:row.list_price,fulfillment_type:row.fulfillment_type,verification_status:row.verification_status,evidence_url:row.evidence_url};try{auditRows.value=(await api('/audit?entity_id='+encodeURIComponent(row.entity_id))).items}catch(caught){modalError.value=caught.message}}
async function saveEdit(){saving.value=true;modalError.value='';try{const changes=Object.fromEntries(Object.entries(editForm.value).filter(([key,value])=>String(value)!==String(editing.value[key])));if(!Object.keys(changes).length)throw Error('请先修改至少一个字段');await api('/catalog/'+domain.value+'/'+encodeURIComponent(editing.value.entity_id),{method:'PATCH',body:JSON.stringify({version:editing.value.version,changes,reason:reason.value})});editing.value=null;await loadProducts();overview.value=await api('/overview');notify('商品已保存，修改记录已写入审计日志')}catch(caught){modalError.value=caught.message}finally{saving.value=false}}
async function openAudit(){try{auditRows.value=(await api('/audit')).items;showAudit.value=true}catch(caught){error.value=caught.message}}
async function previewFile(event){const file=event.target.files[0];if(!file)return;modalError.value='';importRows.value=null;try{if(file.size>500000)throw Error('文件不能超过500KB');importRows.value=await api('/import/preview',{method:'POST',body:JSON.stringify({csv_text:await file.text()})})}catch(caught){modalError.value=caught.message}}
async function applyImport(){importing.value=true;modalError.value='';let saved=0;try{for(const row of importRows.value.items){if(!row.valid)continue;await api('/catalog/internal/'+encodeURIComponent(row.sku_code),{method:'PATCH',body:JSON.stringify({version:row.version,changes:row.changes,reason:'运营CSV批量维护：已预览校验'})});saved++}showImport.value=false;await loadProducts();notify('已保存'+saved+'条商品变更')}catch(caught){modalError.value='已保存'+saved+'条；后续停止：'+caught.message+'。请重新预览剩余记录。';importRows.value=null}finally{importing.value=false}}
async function openOrder(row){detail.value=row;detailRows.value=[];detailLoading.value=true;try{const result=await api('/data/order_lines?order_id='+encodeURIComponent(row.order_id)+'&limit=100');if(detail.value?.order_id===row.order_id)detailRows.value=result.items}catch(caught){error.value=caught.message}finally{detailLoading.value=false}}
async function searchOrders(){if(orderStart.value&&orderEnd.value&&orderStart.value>orderEnd.value){error.value='开始日期不能晚于结束日期';return}error.value='';ordersPage.value=1;appliedOrderFilters.value={q:orderQuery.value,channel:orderChannel.value,start_date:orderStart.value,end_date:orderEnd.value};try{await loadOrders()}catch(caught){error.value=caught.message}}
async function pageOrders(delta){ordersPage.value+=delta;try{await loadOrders()}catch(caught){error.value=caught.message}}
function syncHash(){const id=location.hash.slice(1);if(tabs.some(tab=>tab.id===id))active.value=id}
function closeDialog(event){if(event.key!=='Escape'||saving.value||importing.value)return;editing.value=null;showAudit.value=false;showImport.value=false;detail.value=null;showHelp.value=false;sidebar.value=false}
onMounted(()=>{refresh();window.addEventListener('hashchange',syncHash);window.addEventListener('keydown',closeDialog)})
onUnmounted(()=>{clearTimeout(noticeTimer);window.removeEventListener('hashchange',syncHash);window.removeEventListener('keydown',closeDialog)})
</script>

<template>
<div class="app-shell">
  <aside class="sidebar" :class="{opened:sidebar}">
    <a class="brand" href="#overview" @click.prevent="navigate('overview')"><img class="brand-image" :src="brandAmiya" alt="阿米娅品牌图标" width="45" height="48"/><div>ARKNIGHTS<small>ANALYTICS</small></div></a>
    <div class="workspace-label">商品运营工作空间 <span>V 0.2</span></div>
    <nav aria-label="工作台导航"><button v-for="tab in tabs.filter(tab=>tab.id!=='settings')" :key="tab.id" @click="navigate(tab.id)" :class="{active:active===tab.id}"><component :is="tab.icon" :size="19"/><span>{{ tab.name }}</span><ChevronRight v-if="active===tab.id" :size="14"/></button></nav>
    <div class="sidebar-note"><div class="mini-logo"><Layers3 :size="19"/></div><b>让热爱，有据可循。</b><p>从角色偏好到商品决策<br>连接内容、用户与经营。</p><span>IP MERCH OPERATIONS</span></div>
    <div class="sidebar-bottom"><button @click="navigate('settings')" :class="{active:active==='settings'}"><Settings2 :size="19"/>数据与服务</button><div class="profile"><span class="avatar">L</span><div>lubdbdbd<small>独立项目 · 运营工作台</small></div><span class="online-dot"></span></div></div>
  </aside>
  <div v-if="sidebar" class="sidebar-backdrop" @click="sidebar=false"></div>
  <main>
    <header class="topbar"><div class="breadcrumbs"><button class="icon-btn mobile-menu" @click="sidebar=!sidebar" aria-label="展开导航"><PanelLeftClose :size="20"/></button><span>Arknights Analytics</span><ChevronRight :size="14"/><b>{{ metadata.name }}</b></div><div class="topbar-right"><span class="connection"><i class="online-dot"></i>{{ health?'本地服务已连接':'连接中' }}</span><button class="icon-btn" @click="showHelp=true" aria-label="使用说明"><CircleHelp :size="19"/></button><img class="avatar small profile-image" :src="profileAvatar" alt="lubdbdbd的头像" width="30" height="30"/></div></header>
    <div class="page-content">
      <div class="page-heading"><div><span class="eyebrow">{{ metadata.en }}</span><h1>{{ active==='overview'?'IP周边选品与商品运营分析平台':metadata.name }}</h1><p>{{ {overview:'面向周边商品运营：维护商品、核对经营数据、理解用户需求。',tasks:'跟进商品复核、ERP核对与调研工作，记录负责人、截止日期和交接说明。',products:'为商品上架与日常维护统一角色、品类、价格、授权和履约信息。',erp:'核对订单与库存，比较渠道表现，输出补货和售后处理依据。',research:'用真实问卷验证角色、品类、价格和购买阻力，而不只看内容热度。',selection:'交叉验证内容热度、用户意愿与公开商业信号。',decisions:'核查来源、排名稳定性与SQL口径，把分析建议和真实执行分开。',settings:'查看数据口径、来源与运行状态。'}[active] }}</p></div><button v-if="!['decisions','tasks'].includes(active)" class="button white" @click="refresh" :disabled="busy"><RefreshCw :size="15" :class="{spinning:busy}"/>刷新数据</button></div>
      <div v-if="error" class="error-banner" role="alert">{{ error }} <button @click="refresh">重新加载</button></div>
      <div v-if="busy" class="loading-line" role="status">正在读取本地分析数据…</div>

      <template v-if="active==='overview'&&overview">
        <OperationsBrief :brief="brief" @navigate="openBriefTask"/>
        <section class="hero-strip"><div><span class="hero-kicker">从洞察，到行动</span><h2>用户需求 × 商品供给 × 经营效率</h2><p>聚合角色热度、正版周边调研与ERP经营数据，建立可追溯的选品依据。</p><div class="hero-tags"><span><CheckCircle2 :size="13"/> {{ overview.survey.response_count }}份匿名问卷</span><span><Database :size="13"/> 7类ERP业务表</span><span><ShieldCheck :size="13"/> 商品变更留痕</span></div></div><div class="hero-symbol" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit-center"><Layers3 :size="44"/></div><span class="orbit-point point-a"></span><span class="orbit-point point-b"></span><span class="orbit-number">DATA → DECISION</span></div></section>
        <section class="metric-grid"><article class="metric-card"><div><span>ERP 订单规模</span><Database :size="18"/></div><strong>{{ number(overview.order_count) }}<small>笔</small></strong><footer><span class="badge amber">模拟经营</span><span>订单、库存、售后联查</span></footer></article><article class="metric-card"><div><span>维护中的商品 SKU</span><Package :size="18"/></div><strong>{{ number(overview.sku_count) }}<small>个</small></strong><footer><span class="badge">7 类周边</span><span>19项核心字段规范</span></footer></article><article class="metric-card"><div><span>匿名问卷回收</span><Users :size="18"/></div><strong>{{ number(overview.survey.response_count) }}<small>份</small></strong><footer><span class="badge">真实回收</span><span>高意愿占比 {{ percent(overview.survey.high_intent_share) }}</span></footer></article><article class="metric-card"><div><span>公开商品待维护</span><ShieldCheck :size="18"/></div><strong>{{ overview.maintenance_count }}<small>个</small></strong><footer><span class="badge amber">待复核</span><span>{{ overview.listing_count }}个去重商品档案</span></footer></article></section>
        <section class="dashboard-grid"><article class="panel revenue-panel"><div class="panel-heading"><div><h3>经营走势 <span class="badge amber">模拟 ERP</span></h3><p>{{ overview.date_start }} — {{ overview.date_end }} · 每日支付金额</p></div><button class="text-button" @click="navigate('erp')">查看明细 <ArrowUpRight :size="15"/></button></div><div class="revenue-metrics"><div><span>退款后商品净销售</span><strong>{{ money(overview.revenue) }}</strong></div><div><span>商品毛利</span><strong>{{ money(overview.gross_profit) }}</strong></div><div><span>期末库存成本</span><strong>{{ money(overview.inventory_value) }}</strong></div></div><TrendChart :rows="overview.daily"/><div class="chart-caption"><i></i>每日实付（含运费）<span>历史快照 · 非真实企业收入</span></div></article><article class="panel opportunity-panel"><div class="panel-heading"><div><h3>今日工作清单</h3><p>把数据异常变成可执行动作</p></div><span class="soft-icon"><Activity :size="19"/></span></div><button class="task-card" @click="navigate('products');domain='public'"><span class="task-icon amber"><ShieldCheck :size="20"/></span><div><b>补齐公开商品证据</b><p>{{ overview.maintenance_count }} 个商品需要复核</p></div><ArrowRight :size="16"/></button><button class="task-card" @click="navigate('erp');erpTab='replenishment'"><span class="task-icon"><Package :size="20"/></span><div><b>检查补货与库存风险</b><p>结合在途数量与采购交期</p></div><ArrowRight :size="16"/></button><button class="task-card" @click="navigate('research')"><span class="task-icon blue"><Users :size="20"/></span><div><b>查看用户购买阻力</b><p>用问卷验证商品方向</p></div><ArrowRight :size="16"/></button><div class="insight-note"><span>运营提示</span><p>内容热度代表关注，购买意愿需要独立验证。优先补齐角色 × 品类的专项证据。</p></div></article></section>
        <section class="two-columns"><article class="panel"><div class="panel-heading"><div><h3>用户偏好的角色</h3><p>243份问卷 · Top-3排序加权得分</p></div><button class="text-button" @click="navigate('research')">调研详情 <ArrowUpRight :size="15"/></button></div><Bars :rows="overview.top_operators" label="operator" value="weighted_preference_score" suffix=" 分"/></article><article class="panel"><div class="panel-heading"><div><h3>品类经营贡献</h3><p>退款后净销售 · 模拟ERP</p></div><span class="badge gray">七类正版周边</span></div><Bars :rows="overview.categories.slice(0,5)" label="category" value="net_sales_after_refund" suffix=" 元"/></article></section>
      </template>

      <template v-if="active==='products'">
        <div class="section-notice"><ShieldCheck :size="17"/><span>工作主档修改即时保存；历史 ERP 分析使用原始快照。公开页面的授权标注与人工授权核验分别记录。</span></div>
        <div class="toolbar"><div class="segmented"><button :class="{selected:domain==='internal'}" @click="domain='internal'">内部商品主档</button><button :class="{selected:domain==='public'}" @click="domain='public'">公开商品档案</button></div><div class="toolbar-actions"><button class="button white" @click="openAudit"><Clock3 :size="15"/>修改记录</button><button v-if="domain==='internal'" class="button white" @click="showImport=true;importRows=null;modalError=''"><Upload :size="15"/>批量维护</button><button class="button primary" @click="exportData(domain)"><Download :size="15"/>导出主档</button></div></div>
        <article class="panel table-panel"><div class="filter-bar"><label class="search-box"><Search :size="16"/><input v-model="query" placeholder="搜索商品、角色、SKU编码" aria-label="搜索商品"/></label><select v-model="category" aria-label="筛选商品品类"><option value="">全部品类</option><option v-for="item in [...(health?.categories||[]),'其他正版周边']" :key="item">{{ item }}</option></select><label class="check-filter"><input type="checkbox" v-model="pending"/>{{ domain==='public'?'仅看待人工核验':'仅看规则异常' }}</label><span class="result-count">共 {{ filteredProducts.length }} 个商品</span></div><DataTable :rows="productPage" :columns="productColumns" action="维护" @select="openEditor"/><div class="pagination"><span>{{ domain==='internal'?'模拟ERP商品档案':'真实公开商品快照' }} · 点击表头可排序当前页</span><div><button :disabled="page<=1" @click="page--">上一页</button><span>{{ page }} / {{ Math.max(1,Math.ceil(filteredProducts.length/12)) }}</span><button :disabled="page*12>=filteredProducts.length" @click="page++">下一页</button></div></div></article>
        <div class="two-columns compact-panels"><article class="panel"><h3>主数据维护流程</h3><div class="steps"><span>01 补齐字段</span><ChevronRight :size="15"/><span>02 规则校验</span><ChevronRight :size="15"/><span>03 留痕保存</span></div><p class="muted">售价与成本、库存策略、生命周期进行联合校验。版本校验防止覆盖他人的新修改。</p></article><article class="panel"><h3>授权证据规则</h3><p class="muted">将公开商品标为“已核验”或“已驳回”时，必须填写证据链接与说明。平台记录证据，不会自动证明授权真实。</p><span class="badge gray">公开标注 ≠ 供应商授权证明</span></article></div>
      </template>

      <template v-if="active==='erp'&&overview">
        <div class="section-notice amber"><Database :size="17"/>当前为可复现模拟 ERP 数据，用于验证订单对账、库存分析和售后处理方法。</div>
        <div class="metric-grid"><article class="metric-card slim"><span>订单记录</span><strong>{{ number(overview.order_count) }}</strong><small>跨渠道订单头与明细联查</small></article><article class="metric-card slim"><span>退款后净销售</span><strong>{{ money(overview.revenue) }}</strong><small>已扣除退款 · 不含运费</small></article><article class="metric-card slim"><span>售后退款金额</span><strong>{{ money(overview.refund_amount) }}</strong><small>来自售后与SKU财务汇总</small></article><article class="metric-card slim"><span>建议采购预算</span><strong>{{ money(rows('replenishment').reduce((sum,row)=>sum+(row.suggested_purchase_amount||0),0)) }}</strong><small>结合需求、在途和安全库存</small></article></div>
        <div class="toolbar"><div class="segmented wrap"><button v-for="item in [{id:'orders',label:'订单对账'},{id:'checks',label:'ERP核对中心'},{id:'inventory',label:'库存诊断'},{id:'replenishment',label:'补货计划'},{id:'aftersales',label:'售后分析'},{id:'channels',label:'渠道复盘'}]" :key="item.id" @click="erpTab=item.id;query='';category=''" :class="{selected:erpTab===item.id}">{{ item.label }}</button></div><button v-if="erpTab!=='checks'" class="button primary" @click="exportData(erpTab)"><Download :size="15"/>导出数据</button></div>
        <ErpChecks v-if="erpTab==='checks'"/>
        <article v-else-if="erpTab==='orders'" class="panel table-panel">
          <form class="filter-bar order-filters" @submit.prevent="searchOrders">
            <label class="search-box"><Search :size="16"/><input v-model="orderQuery" placeholder="订单号 / 渠道 / 状态" aria-label="搜索订单"/></label>
            <select v-model="orderChannel" aria-label="订单渠道"><option value="">全部渠道</option><option v-for="item in rows('channels')" :key="item.channel">{{ item.channel }}</option></select>
            <label class="date-filter">从<input v-model="orderStart" type="date" aria-label="订单开始日期"/></label>
            <label class="date-filter">至<input v-model="orderEnd" type="date" aria-label="订单结束日期"/></label>
            <button class="button white" type="submit">查询</button><span class="result-count">{{ number(orderTotal) }} 笔订单</span>
          </form>
          <div v-if="reconciliation" class="reconciliation-strip" :class="{warning:reconciliation.issue_count||reconciliation.global_orphan_line_count}">
            <ShieldCheck :size="20"/><div><strong>已核对 {{ number(reconciliation.checked_count) }} 笔 · {{ number(reconciliation.passed_count) }} 笔通过 · {{ reconciliation.issue_count }} 笔异常</strong><p>当前查询范围实付合计 {{ exactMoney(reconciliation.paid_total) }}。校验商品额、优惠、实付、缺失及重复行；金额容差 ¥0.01。全库孤立明细 {{ reconciliation.global_orphan_line_count }} 条。</p></div>
          </div>
          <DataTable v-if="reconciliation?.issue_count" :rows="reconciliation.issues" :columns="[{key:'order_id',label:'异常订单'},{key:'gross_difference',label:'商品额差值',type:'money'},{key:'discount_difference',label:'优惠差值',type:'money'},{key:'paid_difference',label:'实付差值',type:'money'},{key:'missing_lines',label:'缺失明细'},{key:'duplicate_header',label:'重复表头'},{key:'duplicate_lines',label:'重复明细'},{key:'invalid_header_values',label:'表头数值异常'},{key:'invalid_line_values',label:'明细数值异常'}]"/>
          <DataTable :rows="orderRows" :columns="orderColumns" action="明细" @select="openOrder"/>
          <div class="pagination"><span>导出当前查询范围的全部订单，不受分页限制。</span><div><button :disabled="ordersPage<=1" @click="pageOrders(-1)">上一页</button><span>{{ ordersPage }} / {{ Math.max(1,Math.ceil(orderTotal/20)) }}</span><button :disabled="ordersPage*20>=orderTotal" @click="pageOrders(1)">下一页</button></div></div>
        </article>
        <template v-else-if="erpTab==='channels'">
          <article class="panel table-panel"><div class="panel-heading"><div><h3>渠道经营表现 · 模拟ERP</h3><p>对比支付、客单价与退款；先核对口径，再判断问题。</p></div><span class="badge amber">非真实店铺业绩</span></div><DataTable :rows="rows('channels')" :columns="[{key:'channel',label:'渠道',class:'primary-cell'},{key:'order_count',label:'订单数',type:'number'},{key:'paid_order_count',label:'支付订单数',type:'number'},{key:'payment_rate',label:'订单支付率',type:'percent'},{key:'average_order_value',label:'支付客单价',type:'money'},{key:'refund_amount_rate',label:'退款金额率',type:'percent'},{key:'gross_profit_after_refund_proxy',label:'退款后毛利代理',type:'money'}]"/><p class="metric-definition">订单支付率 = 支付订单数 / 全部订单数，不是访客转化率。退款金额率 = 退款金额 / 商品净收入。毛利代理未计入全部平台费、投流及履约成本，不能称为净利润。</p></article>
          <div class="two-columns"><article class="panel"><h3>直播运营协作准备</h3><p class="muted spaced">{{ brief?.live_boundary }}</p><ol class="help-list"><li v-for="item in brief?.live_checklist" :key="item">{{ item }}</li></ol></article><article class="panel"><h3>当前证据与待接入数据</h3><p v-if="brief?.live_channel" class="muted spaced">模拟“直播间”渠道：{{ brief.live_channel.order_count }}张订单，{{ brief.live_channel.paid_order_count }}张支付订单，订单支付率{{ percent(brief.live_channel.payment_rate) }}。只用于演示复盘方法。</p><p class="muted">没有真实抖音账号、直播场次和流量后台数据，暂不输出点击率、进房率、投流ROI或直播GMV业绩。</p><p class="muted spaced">下一步：获得合规导出的真实场次与渠道数据后，统一时间窗、场次ID、商品ID与退款归属，再进行漏斗复盘。</p></article></div>
        </template>
        <article v-else-if="erpTab!=='aftersales'" class="panel table-panel"><div class="filter-bar"><label class="search-box"><Search :size="16"/><input v-model="query" placeholder="搜索角色、品类或运营建议"/></label><select v-model="category"><option value="">全部品类</option><option v-for="item in health?.categories" :key="item">{{ item }}</option></select><span class="result-count">{{ selectedErp.length }} 个 SKU</span></div><DataTable :rows="selectedErp" :columns="erpTab==='inventory'?inventoryColumns:replenishmentColumns"/></article>
        <template v-else><div class="two-columns"><article class="panel"><div class="panel-heading"><div><h3>主要售后原因</h3><p>品类 × 原因 · 影响件数</p></div></div><Bars :rows="rows('reasons').slice(0,6).map(row=>({...row,label:row.category+' · '+row.reason}))" label="label" value="affected_units"/></article><article class="panel"><div class="panel-heading"><div><h3>渠道退款率</h3><p>退款金额 / 商品净收入</p></div></div><Bars :rows="rows('channels')" label="channel" value="refund_amount_rate" percent/></article></div><article class="panel table-panel"><div class="panel-heading"><h3>售后处理明细</h3><span class="badge gray">{{ rows('aftersales').length }} 条</span></div><DataTable :rows="rows('aftersales')" :columns="[{key:'case_id',label:'售后单',class:'mono'},{key:'order_id',label:'关联订单'},{key:'sku_id',label:'商品',class:'primary-cell'},{key:'reason',label:'原因'},{key:'refund_amount',label:'退款金额',type:'money'},{key:'case_status',label:'状态',type:'badge'}]"/></article></template>
      </template>

      <template v-if="active==='research'&&overview">
        <div class="section-notice"><Users :size="17"/>243份匿名问卷，经批次所有者确认真实回收。便利抽样，结论用于探索，不能代表全体玩家。</div>
        <div class="metric-grid"><article class="metric-card slim"><span>回收样本</span><strong>{{ overview.survey.response_count }}<small>份</small></strong><small>匿名汇总展示</small></article><article class="metric-card slim"><span>18—22岁受访者</span><strong>{{ percent(rows('survey_ages').find(row=>row.age_band.includes('18'))?.respondent_share) }}</strong><small>以大学生群体为主</small></article><article class="metric-card slim"><span>周边购买者</span><strong>{{ number(overview.survey.arknights_merch_buyer_count) }}<small>人</small></strong><small>有明日方舟周边购买经历</small></article><article class="metric-card slim"><span>高购买意愿</span><strong>{{ percent(overview.survey.high_intent_share) }}</strong><small>问卷评分4—5分 · 意愿非成交</small></article></div>
        <div class="two-columns"><article class="panel"><div class="panel-heading"><div><h3>角色偏好排名</h3><p>第一至第三名分别计3 / 2 / 1分</p></div><button class="text-button" @click="exportData('survey_operators')"><Download :size="16"/>导出</button></div><Bars :rows="rows('survey_operators').slice(0,8)" label="operator" value="weighted_preference_score" suffix=" 分"/></article><article class="panel"><div class="panel-heading"><div><h3>什么让用户放弃购买？</h3><p>多选题 · 各项占比不可相加</p></div></div><Bars :rows="rows('survey_barriers').slice(0,8)" label="purchase_barrier" value="respondent_share" percent/></article></div>
        <article class="panel table-panel"><div class="panel-heading"><div><h3>品类需求与价格意愿</h3><p>每项保留样本量，小样本不能直接支持备货</p></div><button class="button white" @click="exportData('survey_categories')"><Download :size="15"/>导出结果</button></div><DataTable :rows="rows('survey_categories')" :columns="[{key:'category',label:'周边品类',class:'primary-cell'},{key:'respondent_count',label:'选择人数',type:'number'},{key:'purchase_intent_mean',label:'平均意愿 / 5',type:'number'},{key:'high_intent_share',label:'高意愿占比',type:'percent'},{key:'median_acceptable_price',label:'可接受价格中位数',type:'money'},{key:'median_preorder_days',label:'预售等待中位天数',type:'number'}]"/></article>
        <div class="two-columns"><article class="panel"><h3>购买渠道偏好</h3><Bars :rows="rows('survey_channels')" label="channel" value="respondent_count" suffix=" 人"/></article><article class="panel"><div class="panel-heading"><div><h3>七品类价格带分布</h3><p>价格区间选择 · 共1,701条观测</p></div><select v-model="category"><option value="">全部品类</option><option v-for="item in health?.categories" :key="item">{{ item }}</option></select></div><DataTable :rows="rows('survey_prices').filter(row=>!category||row.category===category)" :columns="[{key:'category',label:'品类'},{key:'price_band',label:'价格带'},{key:'respondent_count',label:'人数',type:'number'},{key:'category_share',label:'品类内占比',type:'percent'}]"/></article></div>
      </template>

      <template v-if="active==='selection'">
        <div class="section-notice"><ChartNoAxesCombined :size="17"/>需求分用于候选排序；缺失信号显示“—”，不视作零需求。进入备货前仍需专项意向与授权供应商证据。</div>
        <article class="panel table-panel"><div class="filter-bar"><label class="search-box"><Search :size="16"/><input v-model="query" placeholder="搜索干员" aria-label="搜索干员"/></label><span class="result-count">{{ visibleDemand.length }} 名角色 · 多源需求矩阵</span><button class="button primary" @click="exportData('demand')"><Download :size="15"/>导出矩阵</button></div><DataTable :rows="visibleDemand" :columns="demandColumns"/></article>
        <article class="panel table-panel"><div class="panel-heading"><div><h3>角色 × 品类候选组合</h3><p>按当前评估分展示前30项；保留样本量与验证建议</p></div><button class="text-button" @click="exportData('portfolio')">全部导出 <ArrowUpRight :size="15"/></button></div><DataTable :rows="rows('portfolio').slice(0,30)" :columns="[{key:'operator',label:'角色',class:'primary-cell'},{key:'category',label:'品类'},{key:'respondent_count',label:'专项样本',type:'number'},{key:'acceptable_price_median',label:'价格中位数',type:'money'},{key:'portfolio_score',label:'候选分',type:'number'},{key:'portfolio_action',label:'下一步',class:'wide-cell'}]"/></article>
      </template>

      <OperationsTasks v-if="active==='tasks'" @navigate="openBriefTask"/>
      <DecisionEvidence v-if="active==='decisions'"/>
      <LifecycleAnalysis v-if="active==='lifecycle'" ref="lifecycleView"/>
      <GmvDrivers v-if="active==='gmv'" ref="gmvView"/>
      <ChannelStrategy v-if="active==='channels'" ref="channelView"/>
      <BusinessDecisions v-if="active==='business'" ref="businessView"/>

      <template v-if="active==='settings'">
        <div class="two-columns"><article class="panel"><h3>服务运行状态</h3><dl class="service-list"><div><dt>前端工作台</dt><dd>Vue 3 · Vite</dd></div><div><dt>业务 API</dt><dd><i class="online-dot"></i> FastAPI · {{ health?.status }}</dd></div><div><dt>工作主档与修改日志</dt><dd>SQLite · 持久化</dd></div><div><dt>查询缓存</dt><dd>{{ health?.redis }}</dd></div><div><dt>运行模式</dt><dd>{{ health?.mode }}</dd></div></dl><div class="toolbar-actions"><a class="button white" href="/docs" target="_blank" rel="noopener">OpenAPI 文档 <ExternalLink :size="14"/></a><a class="button white" href="/metrics" target="_blank" rel="noopener">Prometheus 指标 <ExternalLink :size="14"/></a></div></article><article class="panel"><h3>数据使用说明</h3><p class="muted spaced">ERP订单、成本与利润来自可复现模拟数据。公开商品保留采集时点信息，展示销量属于代理指标。问卷汇总基于243份用户确认的真实回收。</p><p class="muted">商品维护在独立工作主档中生效，不回写原始采集文件。当前平台用于本地单用户操作；容器部署提供 Nginx、Redis 和 Prometheus 配套服务。</p><span class="badge">原始数据与工作修改分层保存</span></article></div>
        <article class="panel table-panel"><div class="panel-heading"><div><h3>数据来源清单</h3><p>明确每一项结论使用了什么证据</p></div></div><DataTable :rows="rows('evidence')" :columns="[{key:'source',label:'来源',class:'primary-cell'},{key:'scope',label:'范围'},{key:'record_count',label:'记录数',type:'number'},{key:'data_nature',label:'数据性质'},{key:'decision_use',label:'决策用途'}]"/></article>
        <article class="panel table-panel"><div class="panel-heading"><h3>商品主数据字段字典</h3><span class="badge gray">19项字段</span></div><DataTable :rows="rows('dictionary')" :columns="[{key:'field_name',label:'字段',class:'mono'},{key:'field_name_cn',label:'名称'},{key:'business_definition',label:'业务含义',class:'wide-cell'},{key:'validation_rule',label:'校验规则',class:'wide-cell'}]"/></article>
      </template>
      <footer class="site-footer"><span>ARKNIGHTS ANALYTICS <i> / </i> IP周边选品与商品运营分析平台</span><a href="https://github.com/lubdbdbd/ArknightsAnalytics" target="_blank" rel="noopener">开源项目 · lubdbdbd <ArrowUpRight :size="13"/></a></footer>
    </div>
  </main>

  <div v-if="toast" class="toast" role="status"><CheckCircle2 :size="18"/>{{ toast }}</div>
  <div v-if="editing" class="modal-backdrop" @click.self="!saving&&(editing=null)"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><header><div><span class="eyebrow">PRODUCT MAINTENANCE</span><h2 id="edit-title">维护商品信息</h2><p>{{ editing.entity_id }} · 版本 {{ editing.version }}</p></div><button class="icon-btn" @click="editing=null" :disabled="saving" aria-label="关闭"><X/></button></header><form @submit.prevent="saveEdit"><div class="form-grid"><template v-if="domain==='internal'"><label class="full">商品名称<input v-model="editForm.product_name" required/></label><label>供应商编码<input v-model="editForm.supplier_id" required/></label><label>生命周期<select v-model="editForm.sku_status"><option value="active">在售</option><option value="planned">规划中</option><option value="inactive">停售</option></select></label><label>售价（元）<input type="number" step="0.01" min="0.01" v-model.number="editForm.price" required/></label><label>单位成本（元）<input type="number" step="0.01" min="0" v-model.number="editForm.unit_cost" required/></label><label>安全库存<input type="number" step="1" min="0" v-model.number="editForm.safety_stock" required/></label><label>再订货点<input type="number" step="1" min="0" v-model.number="editForm.reorder_point" required/></label><label>采购提前期（天）<input type="number" step="1" min="0" v-model.number="editForm.purchase_lead_time_days" required/></label></template><template v-else><label class="full">商品标题<textarea v-model="editForm.product_title" rows="2" required/></label><label>关联角色<input v-model="editForm.operator" required/></label><label>标准品类<select v-model="editForm.category"><option v-for="item in [...(health?.categories||[]),'其他正版周边']" :key="item">{{ item }}</option></select></label><label>公开展示价格<input type="number" step="0.01" min="0.01" v-model.number="editForm.list_price" required/></label><label>履约类型<select v-model="editForm.fulfillment_type"><option>未标明</option><option>现货/在售</option><option>预售</option><option>补款</option></select></label><label>人工授权核验<select v-model="editForm.verification_status"><option value="pending">待核验</option><option value="verified">已核验</option><option value="rejected">已驳回</option></select></label><label>证据链接<input v-model="editForm.evidence_url" type="url" placeholder="https://…" :required="editForm.verification_status!=='pending'"/></label><a class="source-link full" :href="editing.source_url" target="_blank" rel="noopener">查看原始商品页面 <ExternalLink :size="14"/></a><p class="full muted">{{ editing.maintenance_action }}</p></template><label class="full">修改原因<textarea v-model="reason" minlength="3" maxlength="500" rows="2" placeholder="说明本次修改的依据，至少3个字" required/></label></div><div v-if="modalError" class="error-banner" role="alert">{{ modalError }}</div><div class="form-footer"><span>已记录 {{ auditRows.length }} 次人工修改</span><button class="button primary" :disabled="saving">{{ saving?'保存中…':'保存并记录变更' }}</button></div></form></section></div>
  <div v-if="showAudit" class="modal-backdrop" @click.self="showAudit=false"><section class="modal wide" role="dialog" aria-modal="true" aria-label="商品修改日志"><header><div><span class="eyebrow">AUDIT TRAIL</span><h2>商品修改日志</h2><p>仅展示真实操作产生的记录</p></div><button class="icon-btn" @click="showAudit=false" aria-label="关闭"><X/></button></header><div class="audit-list"><article v-for="row in auditRows" :key="row.audit_id"><div><b>{{ row.entity_id }}</b><span class="badge gray">v{{ row.version }}</span><time>{{ new Date(row.changed_at).toLocaleString('zh-CN') }}</time></div><p>{{ row.reason }}</p><dl><div v-for="(value,key) in JSON.parse(row.after_json)" :key="key"><dt>{{ key }}</dt><dd><del>{{ JSON.parse(row.before_json)[key] }}</del><ArrowRight :size="12"/><strong>{{ value }}</strong></dd></div></dl></article><p v-if="!auditRows.length" class="empty">还没有人工修改。保存商品后，会在这里记录修改前后值、原因与时间。</p></div></section></div>
  <div v-if="showImport" class="modal-backdrop" @click.self="!importing&&(showImport=false)"><section class="modal wide" role="dialog" aria-modal="true" aria-label="CSV批量维护"><header><div><span class="eyebrow">BATCH MAINTENANCE</span><h2>CSV 批量维护</h2><p>先预览校验，再逐条保存有效记录；最多500条</p></div><button class="icon-btn" @click="showImport=false" :disabled="importing" aria-label="关闭"><X/></button></header><p class="muted">第一列使用 sku_code，其他列支持 price、unit_cost、supplier_id、product_name、safety_stock、reorder_point、purchase_lead_time_days、sku_status。只保留要修改的列。</p><pre class="csv-example">sku_code,price,unit_cost
AK-0001,48,16.8</pre><label class="upload-zone"><Upload :size="23"/><span>选择 UTF-8 CSV 文件进行校验</span><input type="file" accept=".csv" @change="previewFile" :disabled="importing"/></label><div v-if="modalError" class="error-banner">{{ modalError }}</div><template v-if="importRows"><p>已检查 {{ importRows.total }} 条，{{ importRows.valid_count }} 条可保存。</p><DataTable :rows="importRows.items.map(row=>({...row,status:row.valid?'校验通过':row.error}))" :columns="[{key:'line',label:'行号'},{key:'sku_code',label:'SKU编码'},{key:'status',label:'校验结果',class:'wide-cell'}]"/><div class="form-footer"><span>无效行不会保存；发生版本冲突时停止后续操作。</span><button class="button primary" :disabled="importing||!importRows.valid_count" @click="applyImport">{{ importing?'保存中…':'保存有效记录' }}</button></div></template></section></div>
  <div v-if="detail" class="modal-backdrop" @click.self="detail=null"><section class="modal wide" role="dialog" aria-modal="true" aria-label="订单明细"><header><div><span class="eyebrow">ORDER RECONCILIATION</span><h2>{{ detail.order_id }}</h2><p>{{ detail.channel }} · {{ detail.order_date }} · 模拟ERP</p></div><button class="icon-btn" @click="detail=null" aria-label="关闭"><X/></button></header><div class="section-notice">实付 {{ exactMoney(detail.paid_amount) }} ｜商品额 {{ exactMoney(detail.order_amount) }} − 优惠 {{ exactMoney(detail.discount_amount) }} + 运费 {{ exactMoney(detail.shipping_fee) }}{{ detail.payment_status==='cancelled'?'（已取消订单，预期实付为0）':'' }}</div><p v-if="detailLoading" class="empty">正在加载订单明细…</p><DataTable v-else :rows="detailRows" :columns="[{key:'sku_id',label:'商品',class:'primary-cell'},{key:'quantity',label:'数量',type:'number'},{key:'unit_price',label:'单价',type:'money'},{key:'discount_amount',label:'优惠',type:'money'},{key:'net_revenue',label:'净收入',type:'money'}]"/></section></div>
  <div v-if="showHelp" class="modal-backdrop" @click.self="showHelp=false"><section class="modal" role="dialog" aria-modal="true" aria-label="使用说明"><header><h2>开始使用运营工作台</h2><button class="icon-btn" @click="showHelp=false" aria-label="关闭"><X/></button></header><ol class="help-list"><li>在“商品信息维护”搜索SKU，修改价格与库存策略，填写依据后保存。</li><li>在“公开商品档案”补充角色、履约和授权证据，在修改日志核对操作。</li><li>在“ERP数据处理”查询订单明细，检查库存分群、补货计划和售后原因。</li><li>在“周边用户调研”比较角色、品类、价格带与购买阻力，再到“角色与选品”查看多源证据。</li></ol><p class="muted">各模块可导出CSV，便于在Excel中进一步分析。</p></section></div>
</div>
</template>
